name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0

      - name: Check Formatting
        if: matrix.os == 'ubuntu-latest'
        run: zig fmt --ast-check --check .

      - name: Build (x86_64-windows)
        run: zig build -Dtarget=x86_64-windows-gnu

      - name: Build (aarch64-windows)
        run: zig build -Dtarget=aarch64-windows-gnu

      - name: Build (x86-windows)
        run: zig build -Dtarget=x86-windows-gnu

      - name: Test
        if: matrix.os == 'windows-latest'
        run: zig build test

      - name: Install Wine
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -cs)/winehq-$(lsb_release -cs).sources
          sudo apt -qq update
          sudo apt -qq install --install-recommends winehq-stable -y
          wine --version

      - name: Test (Wine)
        if: matrix.os == 'ubuntu-latest'
        run: zig build test -Dtarget=x86_64-windows-gnu -fwine
